version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202010-01

    steps:
      - checkout

      - run:
          name: Build Docker containers
          command: |
            set -x
            docker-compose build
            docker-compose run --rm app bash -c "mix --version"
            docker-compose run --rm app mix archive
            docker-compose run --rm app bash -c "node --version && npm --version"

      - run:
          name: Mix deps.get
          command: |
            set -x
            docker-compose run --rm app bash -c "ls && mix deps.get && mix deps.compile"

      - run:
          name: Npm install in assets directory
          command: |
            set -x
            docker-compose run --rm app bash -c "cd assets && ls && npm install && node node_modules/webpack/bin/webpack.js --mode development"

      - run:
          name: Run Docker containers
          command: |
            set -x
            docker-compose up -d
            sleep 5
            docker ps -f status=running
            docker-compose logs

      - run:
          name: Mix format
          command: |
            set -x
            docker-compose exec app bash -c "mix format --check-formatted"

      - run:
          name: Mix test
          command: |
            set -x
            docker-compose exec app bash -c "mix test"

      - run:
          name: Down Docker containers and Finish pipeline
          command: |
            set -x
            docker-compose down --rmi all --volumes --remove-orphans
            echo "Finish pipeline"
